In [134]:
import enigma as en
import numpy as np
from importlib import reload

In [135]:
reload(en)

<module 'enigma' from '/home/august/phd/enigma/enigma.py'>

In [136]:
message = en.Message("augustwollter")
# These parameters describe a rotors initial position, 
# and when the next rotor is advanced
pos = 0
notch = ord('a') - 97
rotorV = en.Rotor(np.identity(26), pos, notch)

In [147]:
t = rotorV.getTransform()
print(en.matrix_to_word(t))
s
m = np.matmul(np.identity(26), t)
m = np.matmul(t,m)
print(en.matrix_to_word(m))

abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz


In [145]:
reload(en)
c = en.cyclic_permutation_matrix('a')
print(c)
type(c)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 

numpy.ndarray

# Cyclic permutatiotns for Rotor I

In [139]:
reload(en)
# Creating Rotor I
t1 = en.cyclic_permutation_matrix('aeltphqxru') 
t2 = en.cyclic_permutation_matrix('bknw') 
t3 = en.cyclic_permutation_matrix('cmoy')
t4 = en.cyclic_permutation_matrix('dfg')
t5 = en.cyclic_permutation_matrix('iv')
t6 = en.cyclic_permutation_matrix('jz')
#s maps to itself
t = np.matmul(t1,t2)
t = np.matmul(t,t3)
t = np.matmul(t,t4)
t = np.matmul(t,t5)
t = np.matmul(t,t6)



In [140]:
reload(en)
rotor1 = en.Rotor(t,0,0)
mess = en.Message('v')

# Reflector

In [141]:
reload(en)
perms = ['ay', 'br', 'cu', 'dh', 'eq', 'fs', 'gl', 
         'ip', 'jx', 'kn', 'mo', 'tz', 'vw']
reflector = en.list_cyclic_permutation_matrix(perms)

In [142]:
reload(en)
reflector = en.Reflector(perms)
rt = reflector.getTransform()
print(rt)
machine = en.Machine([rotor1],reflector)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 

In [143]:
reload(en)
mess = en.Message("a")
machine.transformMessage(mess)
mess

Message: h